### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by EdwardDanielSalazar** [stooged/ESP32-Server-900#4]
Hello, the function cache si disable i'm this update?

**Comment by stooged** [comment]
no, the cache function works fine.

this project had its code merged with the 900u version with the option to enable usb control.
both projects have the same code now


if you change `#define AUTOUSB false` to `#define AUTOUSB true` you will enable usb control which disables cache because cache is not used when usb control is enabled.

if you want cache you must set AUTOUSB to false  `#define AUTOUSB false`

**Comment by EdwardDanielSalazar** [comment]
Ok, understand, thanks, I am trying to add additional code, and it works perfectly, but when trying to load a payload sometimes it loads it and most of the time it doesn't, it could be that the esp32 is saturated, although only that part fails, the rest works, the additional code It's from a temperature sensor and a speed control, would you mind checking the code, I don't want to bother you, I understand if not. anyway you do a great job

**Comment by stooged** [comment]
i tested the wrong code, the cache was not working properly.

i have uploaded the fix.
